// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, email, username, password, lookup_id, bio, profile_picture
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, email, username, password, lookup_id, bio, profile_picture, created_at, updated_at
`

type CreateUserParams struct {
	ID             uuid.UUID
	Email          string
	Username       string
	Password       string
	LookupID       string
	Bio            pgtype.Text
	ProfilePicture pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.LookupID,
		arg.Bio,
		arg.ProfilePicture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.LookupID,
		&i.Bio,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  id, email, username, password, lookup_id, bio, profile_picture, created_at, updated_at
FROM
  users
WHERE
  id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.LookupID,
		&i.Bio,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByLookupID = `-- name: GetUserByLookupID :one
SELECT
  id, email, username, password, lookup_id, bio, profile_picture, created_at, updated_at
FROM
  users
WHERE
  lookup_id = $1
`

func (q *Queries) GetUserByLookupID(ctx context.Context, lookupID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLookupID, lookupID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.LookupID,
		&i.Bio,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
  id, email, username, password, lookup_id, bio, profile_picture, created_at, updated_at
FROM
  users
WHERE
  username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.LookupID,
		&i.Bio,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
