// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             uuid.UUID
	Email          string
	Username       string
	Password       string
	LookupID       string
	Bio            pgtype.Text
	ProfilePicture pgtype.Text
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
